sports_mapping = {
    "americanfootball_cfl": "CFL - Canadian Football League",
    "americanfootball_ncaaf": "NCAAF - US College Football",
    "americanfootball_ncaaf_championship_winner": "NCAAF Championship Winner",
    "americanfootball_nfl": "NFL - US Football",
    "americanfootball_nfl_preseason": "NFL Preseason - US Football",
    "americanfootball_nfl_super_bowl_winner": "NFL Super Bowl Winner",
    "americanfootball_ufl": "UFL - United Football League",
    "aussierules_afl": "AFL - Aussie Football",
    "baseball_kbo": "KBO - KBO League",
    "baseball_milb": "MiLB - Minor League Baseball",
    "baseball_mlb": "MLB - Major League Baseball",
    "baseball_mlb_preseason": "MLB Preseason - Major League Baseball",
    "baseball_mlb_world_series_winner": "MLB World Series Winner",
    "baseball_ncaa": "NCAA Baseball - US College Baseball",
    "baseball_npb": "NPB - Nippon Professional Baseball",
    "basketball_euroleague": "Basketball Euroleague",
    "basketball_nba": "NBA - US Basketball",
    "basketball_nba_championship_winner": "NBA Championship Winner",
    "basketball_nba_preseason": "NBA Preseason - US Basketball",
    "basketball_ncaab": "NCAAB - US College Basketball",
    "basketball_ncaab_championship_winner": "NCAAB Championship Winner",
    "basketball_wnba": "WNBA - US Basketball",
    "boxing_boxing": "Boxing Bouts",
    "cricket_asia_cup": "Asia Cup - Cricket",
    "cricket_big_bash": "Big Bash League - Cricket",
    "cricket_caribbean_premier_league": "CPLT20 - Caribbean Premier League",
    "cricket_icc_world_cup": "ICC World Cup - Cricket",
    "cricket_international_t20": "International Twenty20 - Cricket",
    "cricket_ipl": "IPL - Indian Premier League",
    "cricket_odi": "One Day Internationals - Cricket",
    "cricket_psl": "PSL - Pakistan Super League",
    "cricket_t20_blast": "T20 Blast - Cricket",
    "cricket_test_match": "Test Matches - International Test Matches",
    "cricket_the_hundred": "The Hundred - Cricket",
    "golf_masters_tournament_winner": "Masters Tournament Winner",
    "golf_pga_championship_winner": "PGA Championship Winner",
    "golf_the_open_championship_winner": "The Open Championship Winner",
    "golf_us_open_winner": "US Open Winner",
    "icehockey_nhl": "NHL - US Ice Hockey",
    "icehockey_nhl_championship_winner": "NHL Championship Winner - Stanley Cup Winner",
    "icehockey_sweden_allsvenskan": "HockeyAllsvenskan - Swedish Hockey Allsvenskan",
    "icehockey_sweden_hockey_league": "SHL - Swedish Hockey League",
    "lacrosse_pll": "PLL - Premier Lacrosse League",
    "mma_mixed_martial_arts": "MMA - Mixed Martial Arts",
    "politics_us_presidential_election_winner": "US Presidential Elections Winner",
    "rugbyleague_nrl": "NRL - Aussie Rugby League",
    "soccer_africa_cup_of_nations": "Africa Cup of Nations",
    "soccer_argentina_primera_division": "Primera División - Argentina",
    "soccer_australia_aleague": "A-League - Aussie Soccer",
    "soccer_austria_bundesliga": "Austrian Football Bundesliga",
    "soccer_belgium_first_div": "Belgium First Division A",
    "soccer_brazil_campeonato": "Brasileirão Série A - Brazil",
    "soccer_brazil_serie_b": "Campeonato Brasileiro Série B - Brazil",
    "soccer_chile_campeonato": "Campeonato Chileno - Chile",
    "soccer_china_superleague": "Super League - China",
    "soccer_conmebol_copa_america": "CONMEBOL Copa América",
    "soccer_conmebol_copa_libertadores": "CONMEBOL Copa Libertadores",
    "soccer_denmark_superliga": "Denmark Superliga",
    "soccer_efl_champ": "EFL Championship",
    "soccer_england_efl_cup": "EFL Cup - League Cup",
    "soccer_england_league1": "EFL League 1",
    "soccer_england_league2": "EFL League 2",
    "soccer_epl": "EPL - English Premier League",
    "soccer_fa_cup": "FA Cup - Football Association Challenge Cup",
    "soccer_fifa_world_cup": "FIFA World Cup 2022",
    "soccer_fifa_world_cup_winner": "FIFA World Cup Winner 2026",
    "soccer_fifa_world_cup_womens": "FIFA Women's World Cup",
    "soccer_finland_veikkausliiga": "Veikkausliiga - Finland",
    "soccer_france_ligue_one": "Ligue 1 - France",
    "soccer_france_ligue_two": "Ligue 2 - France",
    "soccer_germany_bundesliga": "Bundesliga - Germany",
    "soccer_germany_bundesliga2": "Bundesliga 2 - Germany",
    "soccer_germany_liga3": "3. Liga - Germany",
    "soccer_greece_super_league": "Super League - Greece",
    "soccer_italy_serie_a": "Serie A - Italy",
    "soccer_italy_serie_b": "Serie B - Italy",
    "soccer_japan_j_league": "J League - Japan",
    "soccer_korea_kleague1": "K League 1 - Korea",
    "soccer_league_of_ireland": "League of Ireland - Airtricity League Premier Division",
    "soccer_mexico_ligamx": "Liga MX - Mexico",
    "soccer_netherlands_eredivisie": "Dutch Eredivisie - Netherlands",
    "soccer_norway_eliteserien": "Eliteserien - Norway",
    "soccer_poland_ekstraklasa": "Ekstraklasa - Poland",
    "soccer_portugal_primeira_liga": "Primeira Liga - Portugal",
    "soccer_spain_la_liga": "La Liga - Spain",
    "soccer_spain_segunda_division": "La Liga 2 - Spain",
    "soccer_spl": "Premiership - Scotland",
    "soccer_sweden_allsvenskan": "Allsvenskan - Sweden",
    "soccer_sweden_superettan": "Superettan - Sweden",
    "soccer_switzerland_superleague": "Swiss Superleague",
    "soccer_turkey_super_league": "Turkey Super League",
    "soccer_uefa_champs_league": "UEFA Champions League",
    "soccer_uefa_champs_league_qualification": "UEFA Champions League Qualification",
    "soccer_uefa_euro_qualification": "UEFA Euro Qualification",
    "soccer_uefa_europa_conference_league": "UEFA Europa Conference League",
    "soccer_uefa_europa_league": "UEFA Europa League",
    "soccer_uefa_european_championship": "UEFA Euro 2024 - European Championship",
    "soccer_uefa_nations_league": "UEFA Nations League",
    "soccer_usa_mls": "MLS - Major League Soccer",
    "tennis_atp_aus_open_singles": "ATP Australian Open - Men's Singles",
    "tennis_atp_french_open": "ATP French Open - Men's Singles",
    "tennis_atp_us_open": "ATP US Open - Men's Singles",
    "tennis_atp_wimbledon": "ATP Wimbledon - Men's Singles",
    "tennis_wta_aus_open_singles": "WTA Australian Open - Women's Singles",
    "tennis_wta_french_open": "WTA French Open - Women's Singles",
    "tennis_wta_us_open": "WTA US Open - Women's Singles",
    "tennis_wta_wimbledon": "WTA Wimbledon - Women's Singles",
}
